name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
        shell: bash
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MNEMONIC: ${{ secrets.MNEMONIC }}
      - name: Run local node and deploy
        shell: bash
        run: |
          npm run dev &
          npm run deploy:dev