name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
        shell: bash
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        file-name: .env
        with:
          ENV_MNEMONIC: ${{ secrets.MNEMONIC }}
      - name: Run Tests
        run: npm run test
      - name: Run Coverage
        run: npm run coverage
