name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
        shell: bash
      - name: Run Tests
        env: 
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: npm run test
      - name: Run Coverage
        env: 
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: npm run coverage
